backup:
  s3:
    endpoint: "" # Will be taken from ENV
    bucket_name: "" # Will be taken from ENV
    region: "auto"
    enabled: true

  databases:
    - type: "mysql"
      enabled: true
      container_name: "mysql"
      db_user: "backuper"
      dump_filename: "db_dump.sql"

  targets:
    - "www"
    - "docker-compose.yml"
  
  telegram:
    enabled: true
    chat_id: "" # Will be taken from ENV

  encryption:
    enabled: false  # Set to true and provide BACKUP_PASSWORD env var to encrypt archives into a .7z file