backup:
  s3:
    endpoint: "" # Will be taken from ENV
    bucket_name: "" # Will be taken from ENV
    region: "auto"
    enabled: true

  databases:
    - type: "mysql"
      enabled: true
      container_name: "mysql"
      db_user: "backuper"
      dump_filename: "db_dump.sql"
      weekdays: ["mon", "wed", "fri"] # Optional: days of week to backup. If omitted, backups up every day.

  targets:
    - path: "www"
      weekdays: ["mon", "tue", "wed", "thu", "fri", "sat", "sun"] # Optional: days of week to backup.
    - path: "docker-compose.yml" # Runs every day if weekdays omitted
  
  telegram:
    enabled: true
    chat_id: "" # Will be taken from ENV

  encryption:
    enabled: false  # Set to true and provide BACKUP_PASSWORD env var to encrypt archives into a .7z file